on: 
  workflow_dispatch :
    inputs:
jobs:
  add_text:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |   
          echo "Hello GitHub Actions!" >> hello.txt
          git ls-files
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
