name: Subtractive Color
on:
  workflow_dispatch :
    inputs:
      texture_path:
        description: "画像のパス"
        required: true
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install ImageMagick
        run: sudo apt install imagemagick # Seems to work and already be included with ubuntu-latest...
      - name: Convert PDF to PNG
#         run: convert ${{ github.event.inputs.texture_path }}.png -depth 8 ${{ github.event.inputs.texture_path }}-depth8.png  
#         run: wc -c ${{ github.event.inputs.texture_path }} | awk '{print $1}'
        run: ls
      - name : test echo
        run: echo ${{ github.event.inputs.texture_path }}
