name: Subtractive Color
on:
  workflow_dispatch :
    inputs:
      texture_path:
        description: "画像のパス"
        required: true
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install ImageMagick
        run: sudo apt install imagemagick # Seems to work and already be included with ubuntu-latest...
      - name: pwd
        run: pwd
#       - name: Convert PDF to PNG
#         run: convert shop_atlas_0.png -depth 8 shop_atlas_0-depth8.png
#         ${{ github.event.inputs.texture_path }}
#       - name : test echo
#         run: echo ${{ github.event.inputs.texture_path }}
